#include <iostream>
using namespace std;

int main() {
  try { //define a block of code to be tested for errors while it is being executed
    int age;
    cout <<"Age: ";
    cin >> age;
    if (age >= 18) {
      cout << "Access granted";
    } else {
      throw (age); //throws an exception when a problem is detected, which lets us create a custom error.
    }
  }
  catch (int myNum) {  //define a block of code to be executed, if an error occurs in the try block.
    cout << "Access denied - You must be at least 18 years old.\n";
    cout << "Age is: " << myNum;  
  }
  return 0;
}
